[tasks.start]
description = "すべての service とミドルウェアをコンテナ起動する"
run = [
    "mise run start-service-a",
    "mise run start-service-b",
    "mise run start-service-c"
]

[tasks.stop]
description = "すべてのコンテナを削除する"
run = [
    """
    echo "Stopping all Docker containers..."
    docker compose down
    """,
    "mise run stop-service-a",
    "mise run stop-service-b",
    "mise run stop-service-c",
    "echo All services stopped."
]


[tasks.start-service-a]
description = "service A をコンテナ起動する"
run = """
echo "Starting shared services..."
docker compose up -d
echo "Starting serviceA..."
docker compose -f serviceA/compose_serviceA.yml up -d
"""

[tasks.stop-service-a]
description = "service A をコンテナ起動する"
run = """
echo "Stopping serviceA..."
docker compose -f serviceA/compose_serviceA.yml down
"""

[tasks.start-service-b]
description = "service B をコンテナ起動する"
run = """
echo "Starting shared services..."
docker compose up -d
echo "Starting serviceB..."
docker compose -f serviceB/compose_serviceB.yml up -d
"""

[tasks.stop-service-b]
description = "service B をコンテナ起動する"
run = """
echo "Stopping serviceB..."
docker compose -f serviceB/compose_serviceB.yml down
"""

[tasks.start-service-c]
description = "service C をコンテナ起動する"
run = """
echo "Starting shared services..."
docker compose up -d
echo "Starting serviceC..."
docker compose -f serviceC/compose_serviceC.yml up -d
"""

[tasks.stop-service-c]
description = "service C をコンテナ起動する"
run = """
echo "Stopping serviceC..."
docker compose -f serviceC/compose_serviceC.yml down
"""