# config/otel-config.yaml
receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
        timeout: 1s
        send_batch_size: 1024

    resource:
        attributes:
            - key: deployment.environment
              value: development
              action: upsert

    memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 25

    # ログ用の属性処理
    attributes/loki:
        actions:
            - key: loki.attribute.labels
              action: insert
              value: service.name, service.instance.id, deployment.environment

exporters:
    # Prometheus Remote Write for metrics
    prometheusremotewrite:
        endpoint: http://prometheus:9090/api/v1/write
        tls:
            insecure: true

    # Tempo exporter for traces
    otlp/tempo:
        endpoint: tempo:4317
        tls:
            insecure: true

    # Loki exporter for logs
    loki:
        endpoint: http://loki:3100/loki/api/v1/push
        # デフォルトラベルの設定
        default_labels_enabled:
            exporter: false
            job: true

    # Debug exporter for troubleshooting
    debug:
        verbosity: basic
        sampling_initial: 5
        sampling_thereafter: 200

extensions:
    health_check:
        endpoint: 0.0.0.0:13133

    zpages:
        endpoint: 0.0.0.0:55679

    pprof:
        endpoint: 0.0.0.0:1777

service:
    extensions: [health_check, zpages, pprof]

    pipelines:
        traces:
            receivers: [otlp]
            processors: [memory_limiter, batch, resource]
            exporters: [otlp/tempo, debug]

        metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch, resource]
            exporters: [prometheusremotewrite, debug]

        logs:
            receivers: [otlp]
            processors: [memory_limiter, batch, resource, attributes/loki]
            exporters: [loki, debug]
