services:
  postgres:
    image: postgres:15
    container_name: serviceA-postgres
    environment:
      POSTGRES_DB: service-a
      POSTGRES_USER: service-a
      POSTGRES_PASSWORD: service-a
    ports:
      - "15432:5432"
    volumes:
      - a_postgres_data:/var/lib/postgresql/data

  servicea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serviceA
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/service-a
      SERVICEB_URL: http://serviceB:8081
      SERVICEC_GRAPHQL_URL: http://serviceC:8082/graphql
      OTEL_SERVICE_NAME: serviceA
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
    ports:
      - "8080:8080"
    volumes:
      # ホスト側の opentelemetry-javaagent.jar をコンテナにマウント
      # 複数のサービスで共通で opentelemetry-javaagent.jar を使用するため一つ上のディレクトリに配置する
      - ../opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar:ro
    depends_on:
      - postgres
    networks:
      - default
      - observability

networks:
  observability:
    external: true
    name: observability-network

volumes:
  a_postgres_data: