spring:
  application:
    name: serviceA
  datasource:
    url: jdbc:postgresql://localhost:15432/service-a
    username: service-a
    password: service-a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # create-drop: アプリ起動時にテーブル作成、終了時に削除（開発用）
      # create: アプリ起動時にテーブル作成（既存データは消去）
      # update: アプリ起動時にテーブル構造を更新（データは保持）
      # validate: アプリ起動時にテーブル構造を検証のみ
      # none: 何もしない（本番環境推奨）
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    # Hibernate がテーブルを作成してから data.sql を実行
    defer-datasource-initialization: true

  # 起動時に data.sql を実行する
  sql:
    init:
      mode: always
server:
    port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE