services:
  postgres:
    image: postgres:15
    container_name: serviceC-postgres
    environment:
      POSTGRES_DB: service-c
      POSTGRES_USER: service-c
      POSTGRES_PASSWORD: service-c
    ports:
      - "35432:5432"
    volumes:
      - c_postgres_data:/var/lib/postgresql/data

  servicec:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serviceC
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/service-c
      OTEL_SERVICE_NAME: serviceC
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    ports:
      - "8082:8082"
    volumes:
      # ホスト側の opentelemetry-javaagent.jar をコンテナにマウント
      # 複数のサービスで共通で opentelemetry-javaagent.jar を使用するため一つ上のディレクトリに配置する
      - ../opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar:ro
    depends_on:
      - postgres
    networks:
      - default
      - observability

networks:
  observability:
    external: true
    name: observability-network

volumes:
  c_postgres_data: